//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Invalidate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Invalidate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Invalidate", typeof(Invalidate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không hợp lệ!.
        /// </summary>
        public static string DeleteInvalidate {
            get {
                return ResourceManager.GetString("DeleteInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã được sử dụng!.
        /// </summary>
        public static string EmailDuplication {
            get {
                return ResourceManager.GetString("EmailDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại!.
        /// </summary>
        public static string EmailNotExist {
            get {
                return ResourceManager.GetString("EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không chính xác!.
        /// </summary>
        public static string IncorrectAccount {
            get {
                return ResourceManager.GetString("IncorrectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm không hợp lệ!.
        /// </summary>
        public static string InsertInvalidate {
            get {
                return ResourceManager.GetString("InsertInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã được sử dụng!.
        /// </summary>
        public static string NumberPhoneDuplication {
            get {
                return ResourceManager.GetString("NumberPhoneDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id người thuê và chủ nhà không được trùng nhau!.
        /// </summary>
        public static string TenantIdAndLandlordIdDuplication {
            get {
                return ResourceManager.GetString("TenantIdAndLandlordIdDuplication", resourceCulture);
            }
        }
    }
}
