//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Successfull {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Successfull() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Successfull", typeof(Successfull).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy thành công..
        /// </summary>
        public static string CancelSucceed {
            get {
                return ResourceManager.GetString("CancelSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu thành công..
        /// </summary>
        public static string ChangePasswordSucceed {
            get {
                return ResourceManager.GetString("ChangePasswordSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công..
        /// </summary>
        public static string DeleteSucceed {
            get {
                return ResourceManager.GetString("DeleteSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác thực email thành công. Bạn có thể đăng nhập..
        /// </summary>
        public static string EmailConfirmSucceed {
            get {
                return ResourceManager.GetString("EmailConfirmSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm theo dõi thành công..
        /// </summary>
        public static string FollowSucceed {
            get {
                return ResourceManager.GetString("FollowSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công..
        /// </summary>
        public static string InsertSucceed {
            get {
                return ResourceManager.GetString("InsertSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập thành công..
        /// </summary>
        public static string LoginSucceed {
            get {
                return ResourceManager.GetString("LoginSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký thành công. Vui lòng xác thực Email để đăng nhập..
        /// </summary>
        public static string RegisterSucceed {
            get {
                return ResourceManager.GetString("RegisterSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gỡ bài đăng thành công..
        /// </summary>
        public static string RemovePost {
            get {
                return ResourceManager.GetString("RemovePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gỡ thành công..
        /// </summary>
        public static string RemoveSucceed {
            get {
                return ResourceManager.GetString("RemoveSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Phản hồi thành công..
        /// </summary>
        public static string ResponseSucceed {
            get {
                return ResourceManager.GetString("ResponseSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu thành công..
        /// </summary>
        public static string SaveSucceed {
            get {
                return ResourceManager.GetString("SaveSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã gửi Email xác thực..
        /// </summary>
        public static string SendEmailSucceed {
            get {
                return ResourceManager.GetString("SendEmailSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy theo dõi thành công..
        /// </summary>
        public static string UnfollowSucceed {
            get {
                return ResourceManager.GetString("UnfollowSucceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công..
        /// </summary>
        public static string UpdateSucceed {
            get {
                return ResourceManager.GetString("UpdateSucceed", resourceCulture);
            }
        }
    }
}
